---
title: "Tarea3_CA0204_C27260"
author: "Emily Sánchez"
subtitle: "CA0204 - Herramientas de Ciencia de Datos I"
institute: "Universidad de Costa Rica"
titlepage: false
editor: visual
format:
  html:
    self-contained: true
    embed-resources: true
---

# 1

```{r}
# Carga de paquetes
library(tidyverse)
library(readr)

# carga de txt a r 
moras <- read_csv("~/Downloads/moras.txt", 
                  col_types =  cols(SALARIO = col_character()))

moras$SALARIO <- gsub(",", ".", moras$SALARIO)


```


# 2

```{r}
# Se agregan un resumen de los 5 números por variable cuantitativa
summary(moras$IDENTIFICACION)

summary(moras$EDAD)

moras$SALARIO <- as.numeric(moras$SALARIO)
summary(moras$SALARIO)

```

# 3

```{r}
library(dplyr)

moras <- moras %>% 
  mutate(
    # Se calcula Z-score para SALARIO y se determinan los valores atípicos.
    # Se usa la formula de Z-score para la media y desviación se omiten los NAs. Note que si el valor era NA se mantendrá como NA.
    ZSCORE_SALARIO = (SALARIO - mean(SALARIO, na.rm = TRUE)) / sd(SALARIO, na.rm = TRUE),
    
    # Se compara con 1.96 los NA siempre quedan como NAs 
    ATIPICO_SALARIO = abs(ZSCORE_SALARIO) > 1.96,
    
    # Análogo a lo de arriba.
    ZSCORE_EDAD = (EDAD - mean(EDAD, na.rm = TRUE)) / sd(EDAD, na.rm = TRUE),
    ATIPICO_EDAD = abs(ZSCORE_EDAD) > 1.96
  )

```

# 4

```{r}
# Se saca el porcentaje de NAs por variable/ columna.
# Se cuentan los NAs por columna, se dividen entre el número total de observaciones y se multiplica por 100 para obtener un porcentaje.
porcentaje_na <- colSums(is.na(moras)) / nrow(moras) * 100
porcentaje_na

```

# 5 
```{r}
# Imputamos las numéricas por el promedio. 
moras$SALARIO <- ifelse(is.na(moras$SALARIO), # Condición lógica
                        mean(moras$SALARIO, na.rm = TRUE), # Si se cumple
                        moras$SALARIO) # Si no se cumple

moras$EDAD <- ifelse(is.na(moras$EDAD), 
                     mean(moras$EDAD, na.rm = TRUE), 
                     moras$EDAD)


# Se crea un función para encontrar la moda de la variable categórica.
moda <- function(x) {
  tab <- table(x)           # Se crea una tabla de frecuencias de cada tipo de aseguramiento.
  names(tab)[which.max(tab)]  # which.max() devuelve la posición del valor máximo en un vector y names (tab) devuelve los nombres de cada elemento de tab. Combinado, esta linea toma los nombres de tab y selecciona el que corresponde a la posición de la frecuencia máxima.
}

# Se imputa con la moda 
moras$TIPO_ASEGURAMIENTO[is.na(moras$TIPO_ASEGURAMIENTO)] <- moda(moras$TIPO_ASEGURAMIENTO)

```


# 6
```{r}
# Se hace una funcion que haga graficos donde se vea la cantidad de individuos por cada variable categórica. 
graficar_categorias <- function(df, var) {
  for (i in var) { # Se recorre cada nombre de cada variable 
    plot <- df %>%
      group_by(.data[[i]]) %>%   # agrupa por las categorías de la variable donde .data[[]] permite acceder los valores que contiene esa variable (columna).
      summarise(cantidad = n()) %>%  # Se cuenta por grupo la cantidad de asegurados.
      ggplot(aes(x = .data[[i]], y = cantidad, fill = .data[[i]])) + # se definen parametros x y y. Se llenan las barras dependiendo de la categoría.
      geom_bar(stat = "identity") + # Para que no cambie los parametros que se definieron en el aes. 
      labs(title = paste("Cantidad de individuos por", i), # titulo 
           x = i,
           y = "Cantidad") +
      theme_minimal() +
      theme(axis.text.x = element_blank()) # se quita los nombres de cada categoría en el eje x porque se ve redundante y para tipo_aseguramiento se ve feo. 
    print(plot)
  }
}

# Se define un vector con las columnas categóricas por graficar
categoricas <- c("SEXO", "SECTOR", "INDICADOR_ACTIVO", 
                 "INDICADOR.EXTRANJERO", "TIPO_ASEGURAMIENTO", 
                 "INDICADOR_MOROSO")

# Se llama a la función
graficar_categorias(moras, categoricas)

```
Note que son los mismos gráficos de excel por lo que es el mismo análisis 

# 7
```{r}
library(scales)
typeof(moras$INDICADOR_MOROSO) # Tipo caracter no funciona para el cálculo 

# Se pasa la variable a numérica para poder usarla en la función
moras$INDICADOR_MOROSO <- ifelse(moras$INDICADOR_MOROSO == "SI", 1,
                                 ifelse(moras$INDICADOR_MOROSO == "NO", 0, NA))

colSums(is.na(moras)) / nrow(moras) * 100  # Se verifica que se haya hecho bien el cambio

# Función para graficar porcentaje de morosos por categoría
graficos_morosos <- function(df, var, indicador_moroso = "INDICADOR_MOROSO") {
  for (i in var) { # Se recorren los nombres de la var por graficar
    # Primero se agrupa por categoría y se calcula el porcentaje de morosos 
    resumen <- df %>%
      group_by(.data[[i]]) %>% # Se agrupan los datos por cada categoría de la variable, se explicó arriba.
      summarise(
        total = n(), # Se explicó arriba
        morosos = sum(.data[[indicador_moroso]] == 1), # Se cuentan las personas morosas, es decir las que tienen como indicador_moroso 1
        porcentaje = morosos / total * 100 # Se calcula el porcentaje dividiendo casos de interes entre casos totales y multiplicando por 100. 
      )
    
    # Luego se crean los gráficos de barras con los datos del tibble de arriba. 
    plot <- ggplot(resumen, aes(x = .data[[i]], y = porcentaje, fill = .data[[i]])) + # se explicó antes 
      geom_bar(stat = "identity") +  # se explicó antes 
      labs(  # se explicó arriba 
        title = paste("Porcentaje de personas morosas por", i),
        x = i,
        y = "Porcentaje (%)"
      ) +
      theme_minimal() +
      theme(axis.text.x = element_blank()) + # se explicó antes 
      scale_y_continuous(breaks = pretty_breaks(n = 10)) # se hacen más ticks para poder ver mejor los porcentajes.(Se usó en el poryecto individual)
    print(plot)
  }
}

# Variables que se van a graficar 
categoricas2 <- c("SEXO", "SECTOR", "INDICADOR_ACTIVO", 
                 "INDICADOR.EXTRANJERO", "TIPO_ASEGURAMIENTO")

# Se llama a la función 
graficos_morosos(moras, categoricas2)
```

Note que son los mismos gráficos de excel por lo que es el mismo análisis 



# 8

```{r}
# Se revierte el cambio que se hizo a la variable INDICADOR_MOROSO en el apartado anterior

moras$INDICADOR_MOROSO <- ifelse(moras$INDICADOR_MOROSO == 1,
                                 "SI",
                                 ifelse(moras$INDICADOR_MOROSO == 0, "NO", NA))

colSums(is.na(moras)) / nrow(moras) * 100  # Se verifica que se haya revertido bien el cambio


# Se calcula la edad promedio por condición de morosidad
edad_promedio <- moras %>%
  group_by(INDICADOR_MOROSO) %>% # Agrupamos a las personas ya sea que son o no morosas
  summarise(promedio = mean(EDAD))  # Se calulan los promedios de edades para cada grupo


# Se trabaja sobre el tibble que se obtuvo arriba
ggplot(edad_promedio,
       aes(x = INDICADOR_MOROSO, y = promedio, fill = INDICADOR_MOROSO)) + # Se explicó antes
  geom_bar(stat = "identity") + # Se explicó antes
  labs(
    title = "Edad promedio según morosidad",
    # Se explicó antes
    x = "Moroso",
    y = "Edad promedio"
  ) +
  theme_minimal() +
  scale_y_continuous(breaks = pretty_breaks(n = 10)) +
  coord_flip() # Se cambian coordenadas para que sea horizontal


# Mismo proceso para salario
salario_promedio <- moras %>%
  group_by(INDICADOR_MOROSO) %>%
  summarise(promedio = mean(SALARIO))


ggplot(salario_promedio,
       aes(x = INDICADOR_MOROSO, y = promedio, fill = INDICADOR_MOROSO)) +
  geom_bar(stat = "identity") +
  labs(title = "Salario promedio según morosidad", x = "Moroso", y = "Salario promedio") +
  theme_minimal() +
  scale_y_continuous(breaks = pretty_breaks(n = 10)) +
  coord_flip() 

```
Note que son los mismos gráficos de excel por lo que es el mismo análisis 









